<#macro display>
<div style="margin-top:auto">

<div class="footer-container">
  <div class="footer-column">
    <strong class="footer-title">Community</strong>
    <div class="footer-icon-row">
      <a href="https://discord.gg/powersync" target="_blank">
        <img src="/images/discord.svg" loading="lazy" alt="Discord" height="24">
      </a>
      <a href="https://twitter.com/powersync_" target="_blank">
        <img src="/images/x.svg" loading="lazy" alt="Twitter" height="20">
      </a>
      <a href="https://www.youtube.com/@powersync_" target="_blank">
        <img src="/images/youtube.svg" loading="lazy" alt="YouTube" width="32" height="28">
      </a>
      <a href="https://www.linkedin.com/showcase/journeyapps-powersync/" target="_blank">
        <img src="/images/linkedin.svg" loading="lazy" alt="LinkedIn" height="24">
      </a>
    </div>
  </div>

  <div class="footer-column">
    <strong class="footer-title">More</strong>
    <div class="footer-icon-row">
      <a href="https://github.com/powersync-ja" target="_blank">
        <img src="/images/github.svg" loading="lazy" alt="GitHub" height="24">
      </a>
      <a href="https://www.powersync.com/" target="_blank">
        <img src="/images/web.svg" loading="lazy" alt="Website" height="30">
      </a>
    </div>
  </div>
</div>

<div class="footer-container">
    <span>© 2025 Journey Mobile, Inc.</span>
    <span class="pull-right">
        <span>Generated by </span>
            <a class="footer--link footer--link_external" href="https://github.com/Kotlin/dokka">
                <span>dokka</span>
            </a>
    </span>
</div>

</div>
</#macro>