name: Publish iOS Swift
on:
  workflow_dispatch:
#  TODO: Uncomment this if we want to publish on merge to main
#  push:
#    branches:
#      - "main"

jobs:
  call-kmmbridge-publish:
    permissions:
      contents: write
      packages: write
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildautoversion.yml@v1.1
    with:
      jvmVersion: 17
      versionBaseProperty: LIBRARY_VERSION
      publishTask: kmmBridgePublish
    secrets:
      gradle_params: -PsigningInMemoryKey="${{ secrets.SIGNING_KEY }}" -PsigningInMemoryKeyId="${{ secrets.SIGNING_KEY_ID }}" -PsigningInMemoryKeyPassword="${{ secrets.SIGNING_PASSWORD }}"
#      PODSPEC_SSH_KEY: ${{ secrets.PODSPEC_SSH_KEY }}
